# Generated by Django 3.0.6 on 2021-12-05 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articale', to=settings.AUTH_USER_MODEL),
        ),
    ]
