# Generated by Django 3.0.6 on 2022-01-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0003_auto_20220104_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequestpost',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
