# Generated by Django 3.0.6 on 2022-01-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0004_bloodrequestpost_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestpost',
            name='currentDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bloodrequestpost',
            name='requestDate',
            field=models.DateTimeField(max_length=50),
        ),
    ]
