# Generated by Django 3.0.6 on 2022-01-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_auto_20211201_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
