# Generated by Django 3.0.6 on 2022-01-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
